import type { Copy } from "./types";

export function copyFor(locale: string): Copy {
  if (locale === "ka") {
    return {
      back: "უკან",
      cancelBooking: "ჯავშნის გაუქმება",
      cancelReasonTitle: "გთხოვთ მოგვაწოდოთ გაუქმების მიზეზი",
      cancelReasonAdmin: "გაუქმების მიზეზი",
      cancelReasonPlaceholder: "დაწერეთ გაუქმების მიზეზი…",
      cancelReasonRequired: "გაუქმების მიზეზი სავალდებულოა",
      cancelFeeKept: "წინასწარი გადახდის მომსახურების თანხა გაუქმების შემთხვევაში არ ბრუნდება.",
      cancelFeeKeptTitle: "არ ბრუნდება",
      cancelRefundableHint: "საიტის საკომისიო ჯავშნის სრულ თანხაზე (ადმინის პროცენტი)",
      cancelHoursLeft: "აღებამდე დარჩენილია დაახლოებით {hours} საათი.",
      cancelUnder48NoProtection:
        "აღებამდე დარჩენილია 48 საათზე ნაკლები. თქვენ არ გაქვთ გაუქმების დაცვა 48 საათზე ადრე გააქტიურებული.",
      cancelUnder2WithProtection:
        "აღებამდე დარჩენილია 2 საათზე ნაკლები. გაუქმების დაცვის მიუხედავად, საიტის მომსახურების საკომისიო არ ბრუნდება.",
      cancelSubmit: "ჯავშნის გაუქმება",
      paid: "აქტიური",
      completed: "დასრულებული",
      pending: "მოლოდინში",
      cancelled: "გაუქმებული",
      partnerCancelled: "პარტნიორის გაუქმებული",
      totalPrice: "ჯამური თანხა",
      priceForDays: "ფასი {n} დღისთვის",
      perDay: "ფასი დღეში",
      toPay: "გადასახდელი",
      amountPaid: "გადახდილი თანხა",
      payAtPickup: "ადგილზე აღებისას გადასახდელი",
      driver: "მძღოლის / მომხმარებლის მონაცემები",
      partner: "მფლობელი",
      partnerCode: "უნიკალური ნომერი",
      company: "საფირმო სახელი",
      phone: "ძირითადი მობილური",
      secondaryPhone: "მეორე ნომერი",
      email: "ელფოსტა",
      name: "სახელი",
      lastName: "გვარი",
      flight: "ფრენის ნომერი",
      birthDate: "დაბადების თარიღი",
      age: "ასაკი",
      residenceCountry: "ვცხოვრობ",
      messenger: "მესენჯერი",
      languages: "სასაუბრო ენები",
      period: "ქირავნობის პერიოდი და ლოკაციები",
      car: "მანქანა",
      options: "დამატებითი ოფციები",
      noOptions: "დამატებითი მომსახურება არ არის",
      pickup: "აღება",
      dropoff: "დაბრუნება",
      editDates: "თარიღებისა და ლოკაციების შეცვლა",
      save: "შენახვა",
      cancel: "გაუქმება",
      location: "ლოკაცია",
      daysCount: "{n} დღე",
      deleteBooking: "ჯავშნის წაშლა",
      deleteConfirm: "ნამდვილად გსურთ ამ ჯავშნის წაშლა?",
      selectedOptions: "არჩეული მომსახურება",
      availableOptions: "დაშვებული მომსახურება ამ მანქანაზე",
      addServices: "მომსახურების დამატება",
      deliveryInfo: "დელივერი",
      deliveryPickupTitle: "მიწოდება (აღება)",
      deliveryReturnTitle: "დაბრუნება",
      dailyTimesDays: "{price} x {n}",
      carRental: "მანქანის ქირა",
      dueWasAtPickup: "ადგილზე იყო გადასახდელი",
      addingServicesValue: "ემატება (დღეები / მომსახურება)",
      payingNow: "ახლა იხდით",
      dueWillAtPickup: "ადგილზე დარჩება გადასახდელი",
      savePayment: "შენახვა გადახდა",
      refundable: "დასაბრუნებელი",
      refundableHint: "საიტის საკომისიო გაუქმებულ სერვისზე / შემცირებულ დღეებზე",
      mandatory: "სავალდებულო",
      mandatoryLocked: "სავალდებულო — წაშლა შეუძლებელია",
      confirmChanges: "კლიენტის ცვლილებების დადასტურება",
      pendingBanner: "კლიენტმა მოითხოვა ცვლილება — დაადასტურეთ",
      refundAlertTitle: "დასაბრუნებელი ცვლილება",
      refundAlertAmount: "გადასარიცხი თანხა",
      refundAlertHint: "დეტალები იხილეთ „დასაბრუნებელი“ ტაბში",
      refundReasonExtras: "გაუქმდა ან შემცირდა ფასიანი მომსახურება",
      refundReasonDays: "შემცირდა ქირავნობის დღეები",
      refundReasonGeneric: "ჯავშნის კორექტირება — საიტის საკომისიოს დაბრუნება",
      viewOnly: "ნახვა მხოლოდ (რედაქტირება არ გაქვთ)",
      daysPriceChange: "დღეებისა და ფასის ცვლილება",
      daysWasNow: "დღეები: {from} → {to} ({delta})",
      rentalWasNow: "ქირა: €{from} → €{to} ({delta})",
      deliveryWasNow: "დელივერი: €{from} → €{to} ({delta})",
      updatedTotal: "განახლებული ჯამი: €{total}",
      daysUnchanged: "დღეების რაოდენობა იგივეა",
      time: "დრო",
      fullTotal: "სრული თანხა",
      partnerGrandTotal: "ჯავშნის ჯამური ფასი",
      partnerPaid: "გადახდილი",
      partnerDueAtPickup: "ადგილზე გადასახდელი",
    };
  }
  if (locale === "ru") {
    return {
      back: "Назад",
      cancelBooking: "Отменить бронь",
      cancelReasonTitle: "Укажите причину отмены",
      cancelReasonAdmin: "Причина отмены",
      cancelReasonPlaceholder: "Напишите причину отмены…",
      cancelReasonRequired: "Причина отмены обязательна",
      cancelFeeKept: "Предоплата за услугу сайта при отмене не возвращается.",
      cancelFeeKeptTitle: "Не возвращается",
      cancelRefundableHint: "Комиссия сайта от полной суммы брони (процент админа)",
      cancelHoursLeft: "До получения осталось примерно {hours} ч.",
      cancelUnder48NoProtection:
        "До получения осталось меньше 48 часов. У вас не активирована защита отмены за 48 часов до начала.",
      cancelUnder2WithProtection:
        "До получения осталось меньше 2 часов. Несмотря на защиту отмены, комиссия сайта не возвращается.",
      cancelSubmit: "Отменить бронь",
      paid: "Активна",
      completed: "Завершено",
      pending: "Ожидание",
      cancelled: "Отменено",
      partnerCancelled: "Отменено партнёром",
      totalPrice: "Итого",
      priceForDays: "Цена за {n} дн.",
      perDay: "Цена / день",
      toPay: "К оплате",
      amountPaid: "Оплачено",
      payAtPickup: "К оплате при получении",
      driver: "Данные водителя / клиента",
      partner: "Владелец",
      partnerCode: "Уникальный номер",
      company: "Фирменное название",
      phone: "Основной мобильный",
      secondaryPhone: "Второй номер",
      email: "Email",
      name: "Имя",
      lastName: "Фамилия",
      flight: "Рейс",
      birthDate: "Дата рождения",
      age: "Возраст",
      residenceCountry: "Я живу в",
      messenger: "Мессенджер",
      languages: "Языки общения",
      period: "Период и локации",
      car: "Авто",
      options: "Доп. опции",
      noOptions: "Нет доп. услуг",
      pickup: "Получение",
      dropoff: "Возврат",
      editDates: "Изменить даты и локации",
      location: "Локация",
      daysCount: "{n} дн.",
      save: "Сохранить",
      cancel: "Отмена",
      deleteBooking: "Удалить бронирование",
      deleteConfirm: "Удалить это бронирование?",
      selectedOptions: "Выбранные услуги",
      availableOptions: "Доступные услуги для авто",
      addServices: "Добавить услуги",
      deliveryInfo: "Доставка",
      deliveryPickupTitle: "Доставка (получение)",
      deliveryReturnTitle: "Возврат",
      dailyTimesDays: "{price} x {n}",
      carRental: "Аренда авто",
      dueWasAtPickup: "Было к оплате на месте",
      addingServicesValue: "Добавка (дни / услуги)",
      payingNow: "Оплачиваете сейчас",
      dueWillAtPickup: "Останется к оплате на месте",
      savePayment: "Сохранить оплату",
      refundable: "К возврату",
      refundableHint: "Сервисный сбор сайта за отменённые услуги / сокращённые дни",
      mandatory: "Обязательно",
      mandatoryLocked: "Обязательно — нельзя удалить",
      confirmChanges: "Подтвердить изменения клиента",
      pendingBanner: "Клиент запросил изменения — подтвердите",
      refundAlertTitle: "Изменение с возвратом",
      refundAlertAmount: "Сумма к возврату",
      refundAlertHint: "Подробности во вкладке «Возвраты»",
      refundReasonExtras: "Отменена или уменьшена платная услуга",
      refundReasonDays: "Сокращён срок аренды",
      refundReasonGeneric: "Корректировка брони — возврат сервисного сбора",
      viewOnly: "Только просмотр",
      daysPriceChange: "Изменение дней и цены",
      daysWasNow: "Дни: {from} → {to} ({delta})",
      rentalWasNow: "Аренда: €{from} → €{to} ({delta})",
      deliveryWasNow: "Доставка: €{from} → €{to} ({delta})",
      updatedTotal: "Обновлённая сумма: €{total}",
      daysUnchanged: "Количество дней без изменений",
      time: "Время",
      fullTotal: "Полная сумма",
      partnerGrandTotal: "Итоговая цена брони",
      partnerPaid: "Оплачено",
      partnerDueAtPickup: "К оплате на месте",
    };
  }
  return {
    back: "Back",
    cancelBooking: "Cancel booking",
    cancelReasonTitle: "Please tell us why you are cancelling",
    cancelReasonAdmin: "Cancellation reason",
    cancelReasonPlaceholder: "Write the cancellation reason…",
    cancelReasonRequired: "A cancellation reason is required",
    cancelFeeKept: "The prepaid site service fee is not refunded on cancellation.",
    cancelFeeKeptTitle: "Not refunded",
    cancelRefundableHint: "Site commission on the full booking total (admin percent)",
    cancelHoursLeft: "About {hours} hours left until pick-up.",
    cancelUnder48NoProtection:
      "Less than 48 hours remain until pick-up. You do not have cancellation protection activated 48 hours before the start.",
    cancelUnder2WithProtection:
      "Less than 2 hours remain until pick-up. Even with cancellation protection, the site service commission is not refunded.",
    cancelSubmit: "Cancel booking",
    paid: "Active",
    completed: "Completed",
    pending: "Pending",
    cancelled: "Cancelled",
    partnerCancelled: "Partner cancelled",
    totalPrice: "Total amount",
    priceForDays: "Price for {n} days",
    perDay: "Price / day",
    toPay: "Amount due",
    amountPaid: "Amount paid",
    payAtPickup: "Due at pick-up",
    driver: "Driver / customer details",
    partner: "Owner",
    partnerCode: "Unique number",
    company: "Trade name",
    phone: "Primary mobile",
    secondaryPhone: "Second number",
    email: "Email",
    name: "First name",
    lastName: "Last name",
    flight: "Flight",
    birthDate: "Date of birth",
    age: "Age",
    residenceCountry: "I live in",
    messenger: "Messenger",
    languages: "Spoken languages",
    period: "Rental period & locations",
    car: "Car",
    options: "Additional options",
    noOptions: "No extra services",
    pickup: "Pick-up",
    dropoff: "Return",
    editDates: "Edit dates & locations",
    location: "Location",
    daysCount: "{n} days",
    save: "Save",
    cancel: "Cancel",
    deleteBooking: "Delete booking",
    deleteConfirm: "Delete this booking?",
    selectedOptions: "Selected services",
    availableOptions: "Services allowed on this car",
    addServices: "Add services",
    deliveryInfo: "Delivery",
    deliveryPickupTitle: "Delivery (Pickup)",
    deliveryReturnTitle: "Return",
    dailyTimesDays: "{price} x {n}",
    carRental: "Car rental",
    dueWasAtPickup: "Was due at pick-up",
    addingServicesValue: "Added (days / services)",
    payingNow: "Paying now",
    dueWillAtPickup: "Will be due at pick-up",
    savePayment: "Save payment",
    refundable: "Refundable",
    refundableHint: "Site service fee on cancelled services / shortened days",
    mandatory: "Mandatory",
    mandatoryLocked: "Mandatory — cannot remove",
    confirmChanges: "Confirm guest changes",
    pendingBanner: "Guest requested changes — please confirm",
    refundAlertTitle: "Refundable change",
    refundAlertAmount: "Amount to return",
    refundAlertHint: "See details in the Refunds tab",
    refundReasonExtras: "Paid service cancelled or reduced",
    refundReasonDays: "Rental period shortened",
    refundReasonGeneric: "Booking correction — site service fee refund",
    viewOnly: "View only (no edit access)",
    daysPriceChange: "Day & price change",
    daysWasNow: "Days: {from} → {to} ({delta})",
    rentalWasNow: "Rental: €{from} → €{to} ({delta})",
    deliveryWasNow: "Delivery: €{from} → €{to} ({delta})",
    updatedTotal: "Updated total: €{total}",
    daysUnchanged: "Number of days unchanged",
    time: "Time",
    fullTotal: "Full total",
    partnerGrandTotal: "Booking total",
    partnerPaid: "Paid",
    partnerDueAtPickup: "Due on site",
  };
}
