/** Catalog of makes → models for partner create-auto and admin category mapping. */

export type CarMakeModels = {
  make: string;
  models: string[];
};

export const CAR_MAKES_MODELS: CarMakeModels[] = [
  {
    make: "Abarth",
    models: ["500", "595", "695", "124 Spider", "Punto", "Fastback"],
  },
  {
    make: "Acura",
    models: ["ILX", "TLX", "RLX", "Integra", "MDX", "RDX", "ZDX", "NSX"],
  },
  {
    make: "Alfa Romeo",
    models: ["Giulia", "Stelvio", "Tonale", "Giulietta", "MiTo", "4C", "159", "Brera", "Spider"],
  },
  {
    make: "Aston Martin",
    models: ["DB11", "DB12", "DBS", "DBX", "Vantage", "Rapide", "Vanquish"],
  },
  {
    make: "Audi",
    models: [
      "A1",
      "A3",
      "A4",
      "A5",
      "A6",
      "A7",
      "A8",
      "Q2",
      "Q3",
      "Q4 e-tron",
      "Q5",
      "Q7",
      "Q8",
      "TT",
      "R8",
      "e-tron",
      "e-tron GT",
      "RS3",
      "RS4",
      "RS5",
      "RS6",
      "RS7",
      "RS Q8",
      "S3",
      "S4",
      "S5",
      "S6",
      "S7",
      "S8",
      "SQ5",
      "SQ7",
      "SQ8",
    ],
  },
  {
    make: "BAIC",
    models: ["X35", "X55", "X7", "BJ40", "EU5", "Senova D50"],
  },
  {
    make: "Bentley",
    models: ["Continental GT", "Flying Spur", "Bentayga", "Mulsanne"],
  },
  {
    make: "BMW",
    models: [
      "1 Series",
      "2 Series",
      "3 Series",
      "4 Series",
      "5 Series",
      "6 Series",
      "7 Series",
      "8 Series",
      "X1",
      "X2",
      "X3",
      "X4",
      "X5",
      "X6",
      "X7",
      "XM",
      "Z4",
      "i3",
      "i4",
      "i5",
      "i7",
      "iX",
      "iX1",
      "iX3",
      "M2",
      "M3",
      "M4",
      "M5",
      "M8",
      "X3 M",
      "X4 M",
      "X5 M",
      "X6 M",
    ],
  },
  {
    make: "BYD",
    models: ["Atto 3", "Dolphin", "Seal", "Seal U", "Han", "Tang", "Song Plus", "Yuan Plus", "Destroyer 05"],
  },
  {
    make: "Cadillac",
    models: ["CT4", "CT5", "CT6", "XT4", "XT5", "XT6", "Escalade", "Lyriq", "Celestiq"],
  },
  {
    make: "Changan",
    models: ["CS35 Plus", "CS55 Plus", "CS75 Plus", "CS95", "Uni-K", "Uni-T", "Uni-V", "Alsvin", "Eado"],
  },
  {
    make: "Chery",
    models: ["Tiggo 2", "Tiggo 4", "Tiggo 7", "Tiggo 8", "Tiggo 8 Pro", "Arrizo 5", "Arrizo 8", "Omoda 5", "Jaecoo 7"],
  },
  {
    make: "Chevrolet",
    models: [
      "Spark",
      "Aveo",
      "Cruze",
      "Malibu",
      "Impala",
      "Camaro",
      "Corvette",
      "Trax",
      "Tracker",
      "Equinox",
      "Blazer",
      "Traverse",
      "Tahoe",
      "Suburban",
      "Colorado",
      "Silverado",
      "Captiva",
      "Orlando",
      "Bolt",
      "Bolt EUV",
    ],
  },
  {
    make: "Chrysler",
    models: ["300", "Pacifica", "Voyager", "Town & Country"],
  },
  {
    make: "Citroen",
    models: [
      "C1",
      "C3",
      "C3 Aircross",
      "C4",
      "C4 Cactus",
      "C4 X",
      "C5",
      "C5 Aircross",
      "C5 X",
      "Berlingo",
      "SpaceTourer",
      "Jumpy",
      "Jumper",
      "Ami",
      "ë-C4",
    ],
  },
  {
    make: "Cupra",
    models: ["Formentor", "Leon", "Ateca", "Born", "Tavascan", "Terramar"],
  },
  {
    make: "Dacia",
    models: ["Sandero", "Sandero Stepway", "Logan", "Duster", "Jogger", "Spring", "Lodgy", "Dokker", "Bigster"],
  },
  {
    make: "Daewoo",
    models: ["Matiz", "Lanos", "Nexia", "Gentra", "Tico", "Espero", "Nubira", "Leganza"],
  },
  {
    make: "Daihatsu",
    models: ["Cuore", "Sirion", "Terios", "Rocky", "Materia", "Charade", "Move", "Taft"],
  },
  {
    make: "Dodge",
    models: ["Charger", "Challenger", "Durango", "Hornet", "Journey", "Ram 1500", "Dart", "Viper"],
  },
  {
    make: "Dongfeng",
    models: ["AX7", "Shine", "S50", "Rich", "Box", "Mage"],
  },
  {
    make: "DS Automobiles",
    models: ["DS 3", "DS 4", "DS 5", "DS 7", "DS 9", "DS 3 Crossback", "DS 7 Crossback"],
  },
  {
    make: "Ferrari",
    models: ["Roma", "Portofino", "SF90", "296 GTB", "F8 Tributo", "812", "Purosangue", "488", "California"],
  },
  {
    make: "Fiat",
    models: [
      "500",
      "500e",
      "500X",
      "500L",
      "Panda",
      "Tipo",
      "Punto",
      "Doblo",
      "Ducato",
      "Fiorino",
      "Scudo",
      "Fullback",
      "Freemont",
      "Bravo",
      "Linea",
    ],
  },
  {
    make: "Ford",
    models: [
      "Fiesta",
      "Focus",
      "Mondeo",
      "Fusion",
      "Mustang",
      "Mustang Mach-E",
      "Puma",
      "EcoSport",
      "Kuga",
      "Escape",
      "Edge",
      "Explorer",
      "Bronco",
      "Bronco Sport",
      "Expedition",
      "Ranger",
      "F-150",
      "Transit",
      "Transit Custom",
      "Tourneo",
      "Tourneo Custom",
      "Tourneo Connect",
      "S-Max",
      "Galaxy",
      "Ka",
      "B-Max",
      "C-Max",
    ],
  },
  {
    make: "GAZ",
    models: ["Gazelle", "Gazelle Next", "Sobol", "Valdai", "Volga"],
  },
  {
    make: "Geely",
    models: ["Coolray", "Atlas", "Atlas Pro", "Monjaro", "Emgrand", "Preface", "Okavango", "Tugella", "Geometry C"],
  },
  {
    make: "Genesis",
    models: ["G70", "G80", "G90", "GV60", "GV70", "GV80", "Electrified G80", "Electrified GV70"],
  },
  {
    make: "GMC",
    models: ["Terrain", "Acadia", "Yukon", "Canyon", "Sierra", "Hummer EV"],
  },
  {
    make: "Great Wall",
    models: ["Wingle", "Poer", "Cannon", "Steed", "Hover H3", "Hover H5", "Hover H6"],
  },
  {
    make: "Haval",
    models: ["Jolion", "H6", "H9", "Dargo", "F7", "F7x", "M6", "H2"],
  },
  {
    make: "Honda",
    models: [
      "Jazz",
      "Fit",
      "Civic",
      "Accord",
      "City",
      "Insight",
      "HR-V",
      "ZR-V",
      "CR-V",
      "Pilot",
      "Passport",
      "Ridgeline",
      "e:Ny1",
      "Honda e",
      "Odyssey",
      "Freed",
      "CR-Z",
    ],
  },
  {
    make: "Hongqi",
    models: ["H5", "H9", "HS5", "HS7", "E-HS9", "E-QM5"],
  },
  {
    make: "Hyundai",
    models: [
      "i10",
      "i20",
      "i30",
      "i40",
      "Accent",
      "Elantra",
      "Sonata",
      "Ioniq",
      "Ioniq 5",
      "Ioniq 6",
      "Kona",
      "Kona Electric",
      "Tucson",
      "Santa Fe",
      "Palisade",
      "Bayon",
      "Venue",
      "Creta",
      "Staria",
      "H-1",
      "H350",
      "Porter",
      "Genesis Coupe",
      "Veloster",
      "Nexo",
    ],
  },
  {
    make: "Infiniti",
    models: ["Q30", "Q50", "Q60", "Q70", "QX30", "QX50", "QX55", "QX60", "QX70", "QX80"],
  },
  {
    make: "Isuzu",
    models: ["D-Max", "MU-X", "Trooper", "NPR", "NQR"],
  },
  {
    make: "Iveco",
    models: ["Daily", "Eurocargo", "Massif"],
  },
  {
    make: "Jaguar",
    models: ["XE", "XF", "XJ", "F-Type", "E-Pace", "F-Pace", "I-Pace", "XK"],
  },
  {
    make: "Jeep",
    models: [
      "Renegade",
      "Compass",
      "Cherokee",
      "Grand Cherokee",
      "Wrangler",
      "Gladiator",
      "Avenger",
      "Commander",
      "Patriot",
      "Liberty",
    ],
  },
  {
    make: "Kia",
    models: [
      "Picanto",
      "Rio",
      "Ceed",
      "Proceed",
      "XCeed",
      "Cerato",
      "Forte",
      "K5",
      "Optima",
      "Stinger",
      "Soul",
      "Seltos",
      "Sportage",
      "Sorento",
      "Telluride",
      "Niro",
      "EV6",
      "EV9",
      "Carnival",
      "Venga",
      "Stonic",
      "Mohave",
      "Bongo",
    ],
  },
  {
    make: "Lada",
    models: ["Granta", "Vesta", "Vesta SW", "XRAY", "Largus", "Niva", "Niva Travel", "Priora", "Kalina", "4x4"],
  },
  {
    make: "Lamborghini",
    models: ["Huracan", "Urus", "Aventador", "Revuelto", "Gallardo"],
  },
  {
    make: "Lancia",
    models: ["Ypsilon", "Delta", "Thema", "Musa"],
  },
  {
    make: "Land Rover",
    models: [
      "Defender",
      "Discovery",
      "Discovery Sport",
      "Range Rover",
      "Range Rover Sport",
      "Range Rover Evoque",
      "Range Rover Velar",
      "Freelander",
    ],
  },
  {
    make: "Lexus",
    models: [
      "CT",
      "IS",
      "ES",
      "GS",
      "LS",
      "RC",
      "LC",
      "UX",
      "NX",
      "RX",
      "GX",
      "LX",
      "RZ",
      "LBX",
      "LM",
      "TX",
    ],
  },
  {
    make: "Li Auto",
    models: ["L6", "L7", "L8", "L9", "MEGA"],
  },
  {
    make: "Lincoln",
    models: ["Corsair", "Nautilus", "Aviator", "Navigator", "MKZ", "Continental"],
  },
  {
    make: "Lotus",
    models: ["Emira", "Eletre", "Evija", "Elise", "Exige", "Evora"],
  },
  {
    make: "Lucid",
    models: ["Air", "Gravity"],
  },
  {
    make: "Maserati",
    models: ["Ghibli", "Quattroporte", "Levante", "Grecale", "MC20", "GranTurismo", "GranCabrio"],
  },
  {
    make: "Mazda",
    models: [
      "Mazda2",
      "Mazda3",
      "Mazda6",
      "MX-5",
      "MX-30",
      "CX-3",
      "CX-30",
      "CX-5",
      "CX-50",
      "CX-60",
      "CX-70",
      "CX-80",
      "CX-9",
      "CX-90",
      "BT-50",
    ],
  },
  {
    make: "McLaren",
    models: ["720S", "750S", "Artura", "GT", "765LT", "Senna"],
  },
  {
    make: "Mercedes-Benz",
    models: [
      "A-Class",
      "B-Class",
      "C-Class",
      "CLA",
      "CLS",
      "E-Class",
      "S-Class",
      "EQA",
      "EQB",
      "EQC",
      "EQE",
      "EQS",
      "EQS SUV",
      "GLA",
      "GLB",
      "GLC",
      "GLE",
      "GLS",
      "G-Class",
      "CLA Shooting Brake",
      "Citan",
      "Vito",
      "V-Class",
      "Viano",
      "Sprinter",
      "X-Class",
      "SL",
      "SLC",
      "AMG GT",
      "CLE",
      "Maybach S-Class",
      "Maybach GLS",
    ],
  },
  {
    make: "MG",
    models: ["MG3", "MG4", "MG5", "ZS", "HS", "Marvel R", "Cyberster", "MG One"],
  },
  {
    make: "MINI",
    models: [
      "Cooper",
      "Cooper S",
      "Cooper SE",
      "Clubman",
      "Countryman",
      "Cabrio",
      "Paceman",
      "John Cooper Works",
      "Aceman",
    ],
  },
  {
    make: "Mitsubishi",
    models: [
      "Space Star",
      "Mirage",
      "Lancer",
      "ASX",
      "Eclipse Cross",
      "Outlander",
      "Outlander PHEV",
      "Pajero",
      "Pajero Sport",
      "L200",
      "Triton",
      "i-MiEV",
      "Colt",
      "Galant",
      "Xpander",
    ],
  },
  {
    make: "Nissan",
    models: [
      "Micra",
      "Note",
      "Almera",
      "Sentra",
      "Altima",
      "Maxima",
      "Leaf",
      "Juke",
      "Qashqai",
      "X-Trail",
      "Rogue",
      "Murano",
      "Pathfinder",
      "Armada",
      "Navara",
      "Frontier",
      "Patrol",
      "Terrano",
      "Primera",
      "Tiida",
      "Teana",
      "Ariya",
      "Townstar",
      "NV200",
      "Interstar",
      "GT-R",
      "370Z",
      "Z",
    ],
  },
  {
    make: "Opel",
    models: [
      "Corsa",
      "Astra",
      "Insignia",
      "Mokka",
      "Crossland",
      "Grandland",
      "Combo",
      "Zafira",
      "Zafira Life",
      "Vivaro",
      "Movano",
      "Adam",
      "Karl",
      "Meriva",
      "Antara",
      "Frontera",
      "Rocks-e",
    ],
  },
  {
    make: "Peugeot",
    models: [
      "108",
      "208",
      "308",
      "408",
      "508",
      "2008",
      "3008",
      "5008",
      "Rifter",
      "Partner",
      "Traveller",
      "Expert",
      "Boxer",
      "e-208",
      "e-2008",
      "e-308",
      "e-Rifter",
      "e-Traveller",
    ],
  },
  {
    make: "Polestar",
    models: ["2", "3", "4", "5"],
  },
  {
    make: "Porsche",
    models: [
      "911",
      "718 Cayman",
      "718 Boxster",
      "Cayman",
      "Boxster",
      "Panamera",
      "Macan",
      "Cayenne",
      "Taycan",
      "918 Spyder",
    ],
  },
  {
    make: "RAM",
    models: ["1500", "2500", "3500", "ProMaster"],
  },
  {
    make: "Renault",
    models: [
      "Clio",
      "Twingo",
      "Zoe",
      "Megane",
      "Megane E-Tech",
      "Fluence",
      "Talisman",
      "Latitude",
      "Captur",
      "Kadjar",
      "Austral",
      "Arkana",
      "Scenic",
      "Espace",
      "Koleos",
      "Duster",
      "Sandero",
      "Logan",
      "Symbol",
      "Trafic",
      "Master",
      "Kangoo",
      "Express",
      "Rafale",
      "5 E-Tech",
    ],
  },
  {
    make: "Rivian",
    models: ["R1T", "R1S", "R2", "R3"],
  },
  {
    make: "Rolls-Royce",
    models: ["Phantom", "Ghost", "Wraith", "Dawn", "Cullinan", "Spectre"],
  },
  {
    make: "Rover",
    models: ["75", "45", "25", "Streetwise"],
  },
  {
    make: "Saab",
    models: ["9-3", "9-5", "900", "9000"],
  },
  {
    make: "Seat",
    models: ["Ibiza", "Leon", "Toledo", "Arona", "Ateca", "Tarraco", "Alhambra", "Mii", "Cordoba", "Exeo"],
  },
  {
    make: "Skoda",
    models: [
      "Citigo",
      "Fabia",
      "Scala",
      "Octavia",
      "Superb",
      "Rapid",
      "Kamiq",
      "Karoq",
      "Kodiaq",
      "Enyaq",
      "Enyaq Coupe",
      "Roomster",
      "Yeti",
      "Elroq",
    ],
  },
  {
    make: "Smart",
    models: ["Fortwo", "Forfour", "#1", "#3"],
  },
  {
    make: "SsangYong",
    models: ["Tivoli", "Korando", "Rexton", "Musso", "Actyon", "Kyron", "Rodius", "Torres"],
  },
  {
    make: "Subaru",
    models: [
      "Impreza",
      "Legacy",
      "Outback",
      "Forester",
      "XV",
      "Crosstrek",
      "Ascent",
      "BRZ",
      "WRX",
      "Levorg",
      "Solterra",
      "Tribeca",
    ],
  },
  {
    make: "Suzuki",
    models: [
      "Alto",
      "Celerio",
      "Swift",
      "Baleno",
      "Ignis",
      "Dzire",
      "SX4",
      "S-Cross",
      "Vitara",
      "Grand Vitara",
      "Jimny",
      "Across",
      "Swace",
      "SX4 S-Cross",
      "Carry",
      "Every",
      "Wagon R",
    ],
  },
  {
    make: "Tesla",
    models: ["Model 3", "Model Y", "Model S", "Model X", "Cybertruck", "Roadster"],
  },
  {
    make: "Toyota",
    models: [
      "Aygo",
      "Aygo X",
      "Yaris",
      "Yaris Cross",
      "Corolla",
      "Corolla Cross",
      "Camry",
      "Avalon",
      "Prius",
      "Prius+",
      "C-HR",
      "RAV4",
      "Highlander",
      "Land Cruiser",
      "Land Cruiser Prado",
      "Fortuner",
      "4Runner",
      "Sequoia",
      "Hilux",
      "Tacoma",
      "Tundra",
      "Proace",
      "Proace City",
      "Proace Verso",
      "Hiace",
      "Sienna",
      "Alphard",
      "Venza",
      "bZ4X",
      "Supra",
      "GR86",
      "GR Yaris",
      "GR Corolla",
      "Auris",
      "Avensis",
      "Verso",
      "Urban Cruiser",
    ],
  },
  {
    make: "UAZ",
    models: ["Patriot", "Hunter", "Pickup", "Bukhanka", "Profi"],
  },
  {
    make: "Vauxhall",
    models: ["Corsa", "Astra", "Insignia", "Mokka", "Crossland", "Grandland", "Combo", "Vivaro", "Movano"],
  },
  {
    make: "Volkswagen",
    models: [
      "up!",
      "Polo",
      "Golf",
      "Golf GTI",
      "Golf R",
      "Jetta",
      "Passat",
      "Arteon",
      "Scirocco",
      "Beetle",
      "T-Cross",
      "T-Roc",
      "Taigo",
      "Tiguan",
      "Tiguan Allspace",
      "Touareg",
      "Touran",
      "Sharan",
      "Multivan",
      "California",
      "Caravelle",
      "Transporter",
      "Caddy",
      "Crafter",
      "Amarok",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.7",
      "ID.Buzz",
      "ID.6",
      "Atlas",
      "Teramont",
      "Tayron",
    ],
  },
  {
    make: "Volvo",
    models: [
      "S60",
      "S90",
      "V40",
      "V60",
      "V90",
      "XC40",
      "XC60",
      "XC90",
      "C40",
      "EX30",
      "EX90",
      "EM90",
      "XC70",
      "S40",
      "S80",
    ],
  },
  {
    make: "VW",
    models: [
      "up!",
      "Polo",
      "Golf",
      "Jetta",
      "Passat",
      "Arteon",
      "T-Cross",
      "T-Roc",
      "Taigo",
      "Tiguan",
      "Touareg",
      "Touran",
      "Sharan",
      "Multivan",
      "California",
      "Caravelle",
      "Transporter",
      "Caddy",
      "Crafter",
      "Amarok",
      "ID.3",
      "ID.4",
      "ID.5",
      "ID.7",
      "ID.Buzz",
    ],
  },
  {
    make: "Zeekr",
    models: ["001", "007", "009", "X", "7X"],
  },
];

export type MappedCarModel = { make: string; model: string };

export function modelKey(make: string, model: string) {
  return `${make.trim().toLowerCase()}::${model.trim().toLowerCase()}`;
}
