"use client";

import { useAdminLocale } from "@/components/providers/admin-locale-context";
import { uiText } from "@/lib/i18n/ui-text";

/** Business-partner admin windows follow the admin language (other locales use English). */
export function useBpLabels() {
  const { locale } = useAdminLocale();
  const t = (en: string, ka: string, ru: string) => uiText(locale, en, ka, ru);
  return {
    locale,
    invoice: t("Invoice", "ინვოისი", "Счёт"),
    invoiceHint: t(
      "Earned amount",
      "გამომუშავებული თანხა",
      "Заработанная сумма",
    ),
    dueTotal: t("Total to transfer", "გადასარიცხი სულ", "К переводу всего"),
    records: t("records", "ჩანაწერი", "записей"),
    minDue: t("Min. to transfer ($)", "მინ. გადასარიცხი ($)", "Мин. к переводу ($)"),
    example100: t("e.g. 100", "მაგ. 100", "напр. 100"),
    sortPrice: t("Sort by amount", "ფასის დალაგება", "Сортировка по сумме"),
    highToLow: t("High → low", "მაღალი → დაბალი", "Сначала больше"),
    lowToHigh: t("Low → high", "დაბალი → მაღალი", "Сначала меньше"),
    partner: t("Partner", "პარტნიორი", "Партнёр"),
    country: t("Country", "ქვეყანა", "Страна"),
    code: t("Code", "კოდი", "Код"),
    bookings: t("Bookings", "ჯავშნები", "Брони"),
    earned: t("Earned", "გამომუშავება", "Заработок"),
    paid: t("Paid", "გადახდილი", "Выплачено"),
    due: t("To transfer", "გადასარიცხი", "К переводу"),
    details: t("Details", "დეტალები", "Детали"),
    transfer: t("Transfer", "გადარიცხვა", "Перевод"),
    delete: t("Delete", "წაშლა", "Удалить"),
    deleteFailed: t("Could not delete", "წაშლა ვერ მოხერხდა", "Не удалось удалить"),
    confirmDelete: t(
      "Delete this partner?",
      "ნამდვილად გსურთ პარტნიორის წაშლა?",
      "Удалить этого партнёра?",
    ),
    noEarners: t(
      "No partners with earnings yet.",
      "გამომუშავებული თანხის მქონე პარტნიორი არ არის.",
      "Партнёров с заработком пока нет.",
    ),
    loading: t("Loading…", "იტვირთება…", "Загрузка…"),
    save: t("Save", "შენახვა", "Сохранить"),
    saving: t("Saving…", "ინახება…", "Сохранение…"),
    saved: t("Saved", "შენახულია", "Сохранено"),
    saveFailed: t("Could not save", "შენახვა ვერ მოხერხდა", "Не удалось сохранить"),
    close: t("Close", "დახურვა", "Закрыть"),
    search: t("Search", "ძებნა", "Поиск"),
    history: t("History", "ისტორია", "История"),
    historyBody: t(
      "Bookings whose partner transfer is already complete.",
      "ჯავშნები, რომლებზეც პარტნიორის გადარიცხვა უკვე დასრულებულია.",
      "Брони, по которым перевод партнёру уже завершён.",
    ),
    historySearch: t(
      "Booking, partner, customer…",
      "ჯავშანი, პარტნიორი, კლიენტი…",
      "Бронь, партнёр, клиент…",
    ),
    booking: t("Booking", "ჯავშანი", "Бронь"),
    date: t("Date", "თარიღი", "Дата"),
    airport: t("Airport", "აეროპორტი", "Аэропорт"),
    customer: t("Customer", "კლიენტი", "Клиент"),
    transferred: t("Transferred", "გადარიცხული", "Переведено"),
    transferredTotal: t("transferred total", "გადარიცხული ჯამი", "переведено всего"),
    noHistory: t(
      "No completed transfer bookings yet.",
      "დასრულებული გადარიცხვის ჯავშანი ჯერ არ არის.",
      "Завершённых переводов пока нет.",
    ),
    balanceTitle: t("Balance to transfer", "გადასარიცხი ბალანსი", "Баланс к переводу"),
    balanceTotal: t("Total to transfer:", "სულ გადასარიცხი:", "Всего к переводу:"),
    balanceEmpty: t(
      "No bookings left on the balance.",
      "გადასარიცხი ჯავშანი ბალანსზე არ არის.",
      "На балансе нет броней к переводу.",
    ),
    bookingsLoadFailed: t(
      "Could not load bookings",
      "ჯავშნები ვერ ჩაიტვირთა",
      "Не удалось загрузить брони",
    ),
    moderationTitle: t(
      "New partner moderation",
      "ახალი პარტნიორების მოდერაცია",
      "Модерация новых партнёров",
    ),
    moderationBody: t(
      "Approve or reject applications from /partnership.",
      "დაამტკიცეთ ან უარყავით /partnership-დან შემოსული განაცხადები.",
      "Одобряйте или отклоняйте заявки с /partnership.",
    ),
    moderationEmpty: t(
      "No partners waiting for moderation.",
      "მოდერაციის მოლოდინში პარტნიორი არ არის.",
      "Нет партнёров на модерации.",
    ),
    note: t("Note", "შენიშვნა", "Заметка"),
    approve: t("Approve", "დამტკიცება", "Одобрить"),
    reject: t("Reject", "უარყოფა", "Отклонить"),
    updateFailed: t("Update failed", "განახლება ვერ მოხერხდა", "Не удалось обновить"),
    countriesTitle: t("Program countries", "პროგრამის ქვეყნები", "Страны программы"),
    countriesBody: t(
      "Countries where the business-partner program is available.",
      "რომელ ქვეყნებში არის ხელმისაწვდომი ბიზნეს პარტნიორის პროგრამა.",
      "Страны, где доступна программа бизнес-партнёров.",
    ),
    pickCountry: t(
      "Select at least one country",
      "აირჩიეთ მინიმუმ ერთი ქვეყანა",
      "Выберите хотя бы одну страну",
    ),
    selectedCountries: t("Selected", "არჩეულია", "Выбрано"),
    countriesWord: t("countries", "ქვეყანა", "стран"),
    transferTitle: t(
      "Transfer funds to partner",
      "თანხის გადარიცხვა პარტნიორისთვის",
      "Перевод средств партнёру",
    ),
    partnerPaypal: t("Partner PayPal:", "პარტნიორის PayPal:", "PayPal партнёра:"),
    paypalMissing: t(
      "Partner has no PayPal email",
      "პარტნიორს PayPal მეილი არ აქვს შევსებული",
      "У партнёра не указан PayPal",
    ),
    amountRange: t(
      "Amount must be greater than 0 and ≤",
      "თანხა უნდა იყოს 0-ზე მეტი და ≤",
      "Сумма должна быть больше 0 и ≤",
    ),
    transferFailed: t("Transfer failed", "გადარიცხვა ვერ მოხერხდა", "Перевод не выполнен"),
    transferredOk: t("Transferred", "გადაირიცხა", "Переведено"),
    balanceDue: t("Balance to transfer:", "გადასარიცხი ნაშთი:", "Остаток к переводу:"),
    amountLabel: t("Amount to transfer ($):", "გადასარიცხი თანხა ($):", "Сумма перевода ($):"),
    paypalSend: t("Send with PayPal", "PayPal-ით გადარიცხვა", "Отправить через PayPal"),
    working: t("Working…", "მიმდინარეობს…", "Выполняется…"),
    confirmLedger: t(
      "Confirm in the ledger",
      "ჩანაწერში დადასტურება",
      "Подтвердить в журнале",
    ),
    name: t("Name", "სახელი", "Имя"),
    cabinetLogin: t("Cabinet login", "კაბინეტის შესვლა", "Вход в кабинет"),
    login: t("Login", "ლოგინი", "Логин"),
    password: t("Password", "პაროლი", "Пароль"),
    newPassword: t("New password", "ახალი პაროლი", "Новый пароль"),
    passwordRequired: t("Enter a password", "შეიყვანეთ პაროლი", "Введите пароль"),
    passwordRules: t(
      "Password must be at least 6 characters and include a letter and a digit",
      "პაროლი უნდა იყოს მინ. 6 სიმბოლო, ლათინური ასო და ციფრი",
      "Пароль: минимум 6 символов, буква и цифра",
    ),
    passwordSaved: t("Password saved", "პაროლი შენახულია", "Пароль сохранён"),
    phone: t("Phone", "ტელეფონი", "Телефон"),
    email: t("Email", "ელ. ფოსტა", "Email"),
    messengers: t("Messengers", "მესენჯერები", "Мессенджеры"),
    website: t("Website / social page", "ვებგვერდი / სოც. გვერდი", "Сайт / соцсеть"),
    personalId: t("Personal ID", "პირადი ნომერი", "Личный номер"),
    payoutMethod: t("Payout method", "გადახდის მეთოდი", "Способ выплаты"),
    bankTransfer: t("Bank transfer", "საბანკო გადარიცხვა", "Банковский перевод"),
    iban: t("IBAN", "IBAN (ანგარიში)", "IBAN"),
    swift: t("SWIFT / BIC", "SWIFT / BIC", "SWIFT / BIC"),
    applicantDetails: t("Applicant details", "განმცხადებლის მონაცემები", "Данные заявителя"),
    social: t("Social", "სოც. ქსელი", "Соцсеть"),
    category: t("Category", "კატეგორია", "Категория"),
    referralCode: t("Referral code", "რეფერალური კოდი", "Реферальный код"),
    status: t("Status", "სტატუსი", "Статус"),
    created: t("Created", "შექმნილია", "Создано"),
    updated: t("Updated", "განახლებულია", "Обновлено"),
    referralLink: t("Referral link", "რეფერალური ბმული", "Реферальная ссылка"),
    notifyEmail: t("Notification email", "შეტყობინების მაილი", "Email уведомлений"),
    badEmail: t("Invalid email", "არასწორი მაილი", "Некорректный email"),
    adminPaypal: t("Administrator PayPal email", "ადმინისტრატორის PayPal მეილი", "PayPal администратора"),
    badPaypal: t("Invalid PayPal email", "არასწორი PayPal მაილი", "Некорректный PayPal"),
    minEarned: t("Min. earnings ($)", "მინ. გამომუშავება ($)", "Мин. заработок ($)"),
    earnedAbove: t("earnings >", "გამომუშავება >", "заработок >"),
    noneAbove: t(
      "No partner earned more than this threshold.",
      "ამ ზღვარზე მეტი გამომუშავების მქონე პარტნიორი არ არის.",
      "Нет партнёров с заработком выше этого порога.",
    ),
    avgBooking: t("Avg. booking", "საშ. ჯავშანი", "Средняя бронь"),
    bookingsInFilter: t("bookings in filter", "ჯავშანი ფილტრში", "броней в фильтре"),
    programRate: t(
      "Program rate (no bookings)",
      "პროგრამის ტარიფი (ჯავშანი არ არის)",
      "Тариф программы (броней нет)",
    ),
    siteShare: t("Site share", "საიტის წილი", "Доля сайта"),
    perBooking: t("Per booking", "ჯავშანზე", "За бронь"),
    siteCommission: t("site commission", "საიტის საკომისიო", "комиссия сайта"),
    totalWord: t("total", "ჯამი", "итого"),
    partnerShare: t("Partner share", "პარტნიორის წილი", "Доля партнёра"),
    customerDiscount: t("Customer discount", "კლიენტის ფასდაკლება", "Скидка клиента"),
    categoryIncome: t(
      "Categories by earnings",
      "კატეგორიები შემოსავლის მიხედვით",
      "Категории по заработку",
    ),
    categoryTotalFiltered: t(
      "Category earnings for this filter:",
      "კატეგორიების ჯამური გამომუშავება ფილტრის მიხედვით:",
      "Суммарный заработок категорий по фильтру:",
    ),
    byFilter: t("By filter", "ფილტრის მიხედვით", "По фильтру"),
    partners: t("Partners", "პარტნიორები", "Партнёры"),
    share: t("Share", "წილი", "Доля"),
    noCategoryData: t(
      "No category data for this filter.",
      "ამ ფილტრით კატეგორიის მონაცემი არ არის.",
      "Нет данных по категориям для этого фильтра.",
    ),
    topEarners: t("Top 20 by earnings", "ტოპ 20 გამომუშავებით", "Топ 20 по заработку"),
    topEarnersBody: t(
      "By filter — partners with the highest earnings (max 20).",
      "ფილტრის მიხედვით — ყველაზე მეტი გამომუშავებული პარტნიორი (მაქს. 20).",
      "По фильтру — партнёры с наибольшим заработком (макс. 20).",
    ),
    noPartnersFilter: t(
      "No partners match this filter.",
      "ამ ფილტრით პარტნიორი არ მოიძებნა.",
      "По этому фильтру партнёры не найдены.",
    ),
    tiersTitle: t(
      "Partner share by monthly bookings",
      "პარტნიორის წილი თვიური ჯავშნებით",
      "Доля партнёра по броням за месяц",
    ),
    tiersFrom: t("of the site 15%", "საიტის 15%-დან", "от 15% сайта"),
    defaults: t("Defaults", "ნაგულისხმევი", "По умолчанию"),
    low: t("Low", "დაბალი", "Низкий"),
    mid: t("Medium", "საშუალო", "Средний"),
    high: t("High", "მაღალი", "Высокий"),
    perMonth: t("/ month", "/ თვე", "/ мес."),
    maxBookings: t("Max bookings", "მაქს. ჯავშნები", "Макс. брони"),
    percent: t("Percent", "პროცენტი", "Процент"),
    lowMax: t("Low max", "დაბალი მაქს", "Низкий макс."),
    midMax: t("Medium max", "საშუალო მაქს", "Средний макс."),
    lowPercent: t("Low %", "დაბალი %", "Низкий %"),
    midPercent: t("Medium %", "საშუალო %", "Средний %"),
    highPercent: t("High %", "მაღალი %", "Высокий %"),
    startDate: t("Start date", "საწყისი თარიღი", "Дата начала"),
    endDate: t("End date", "საბოლოო თარიღი", "Дата окончания"),
    partnerCountry: t("Partner country", "პარტნიორის ქვეყანა", "Страна партнёра"),
    allCountriesSearch: t(
      "All countries — type to search",
      "ყველა ქვეყანა — აკრიფეთ საძებნელად",
      "Все страны — начните ввод",
    ),
    allCountries: t("All countries", "ყველა ქვეყანა", "Все страны"),
    noCountryMatch: t("No matching countries", "ქვეყანა ვერ მოიძებნა", "Страны не найдены"),
    allCategories: t("All categories", "ყველა კატეგორია", "Все категории"),
    searchPlaceholder: t(
      "Name, email, phone, code…",
      "სახელი, მეილი, ტელეფონი, კოდი…",
      "Имя, email, телефон, код…",
    ),
    applyFilters: t("Apply filters", "ფილტრის გამოყენება", "Применить фильтры"),
    newListing: t("New listing", "ახალი განცხადება", "Новое объявление"),
    correction: t("Update", "კორექტირება", "Правка"),
    insuranceUntil: t("Insurance until:", "დაზღვევის ვადა:", "Страховка до:"),
    rejectTitle: t("Rejection message", "უარყოფის შეტყობინება", "Сообщение об отказе"),
    rejectBody: t(
      "Say why the profile was not updated. The partner will receive this message",
      "მიუთითეთ, რის გამო არ მოხდა პროფილის განახლება. შეტყობინება გაეგზავნება პარტნიორს",
      "Укажите, почему профиль не обновлён. Сообщение уйдёт партнёру",
    ),
    rejectPlaceholder: t(
      "e.g. Changing currency needs extra documents…",
      "მაგ.: ვალუტის შეცვლა საჭიროებს დამატებით დოკუმენტაციას…",
      "напр.: смена валюты требует дополнительных документов…",
    ),
    rejectNeedNote: t(
      "A message to the partner is required to reject",
      "უარყოფისთვის საჭიროა შეტყობინება პარტნიორისთვის",
      "Для отказа нужно сообщение партнёру",
    ),
    rejectSent: t(
      "Changes rejected — the partner was notified",
      "ცვლილებები უარყოფილია — პარტნიორს გაეგზავნა შეტყობინება",
      "Изменения отклонены — партнёру отправлено сообщение",
    ),
    sendReject: t("Send and reject", "გაგზავნა და უარყოფა", "Отправить и отклонить"),
    cancel: t("Cancel", "გაუქმება", "Отмена"),
    adminChatId: t("Administrator Telegram chat ID", "ადმინისტრატორის Telegram chat ID", "Telegram chat ID администратора"),
    adminChatPlaceholder: t("e.g. 123456789", "მაგ. 123456789", "напр. 123456789"),
    actions: t("Actions", "მოქმედებები", "Действия"),
    refresh: t("Refresh", "განახლება", "Обновить"),
    adminChatHelp: t(
      "Send /start ADMIN to the bot, or paste the chat ID here. New bookings, changes, and live-chat operator requests arrive here.",
      "ბოტში გაგზავნეთ /start ADMIN, ან ჩაწერეთ chat ID აქ. ახალი ჯავშანი, ცვლილება და live-chat ოპერატორის მოთხოვნა აქ მოვა.",
      "Отправьте боту /start ADMIN или вставьте chat ID. Сюда придут новые брони, изменения и запросы оператора live-chat.",
    ),
  };
}
